version: '3'
services:
  deep-learning-course:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./:/app  # Replace with the actual path on your host machine

